[package]
name = "mckerel-protocol-macros"
version = "0.1.0"
authors = ["kijetesantakalu <ebomberger@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"
darling = "0.13"